// Curated list of Australian SMB industries.
// Used for the built-in "industry" intake question type.

export const INDUSTRIES: string[] = [
  "Accounting & Bookkeeping",
  "Agriculture & Farming",
  "Architecture & Design",
  "Automotive & Mechanic",
  "Beauty & Hairdressing",
  "Childcare & Education",
  "Cleaning Services",
  "Construction & Building",
  "Consulting & Professional Services",
  "Dental & Medical",
  "Electrician & Electrical Services",
  "Engineering",
  "Events & Entertainment",
  "Finance & Insurance",
  "Fitness & Personal Training",
  "Food & Hospitality (Café, Restaurant)",
  "Government & Non-profit",
  "Health & Wellness",
  "Hospitality & Accommodation",
  "Information Technology / IT Services",
  "Landscaping & Gardening",
  "Law & Legal Services",
  "Logistics & Transport",
  "Manufacturing",
  "Marketing & Advertising",
  "Mining & Resources",
  "Photography & Videography",
  "Plumbing",
  "Property & Real Estate",
  "Recruitment & HR",
  "Retail (Bricks & Mortar)",
  "Retail (E-commerce)",
  "Tourism & Travel",
  "Trades — General",
  "Veterinary & Pet Services",
  "Wholesale & Distribution",
  "Other",
]
